services:
  extraction:
    image: extract:latest
    volumes:
      - $HOME/.aws:/root/.aws
      - $PWD/data_processing:/data_collection
  transformation:
    image: transform:beta
    depends_on:
      extraction:
        condition: service_completed_successfully
        restart: true
    volumes:
      - $HOME/.aws:/root/.aws
  loading:
    image: load:latest
    depends_on:
      transformation:
        condition: service_completed_successfully
        restart: true
    volumes:
      - $HOME/.snowflake:/root/.snowflake
      - $PWD/data_processing:/data_loading

  trading_bot:
    image: trading_bot:alpha
    depends_on:
      loading:
        condition: service_completed_successfully
        restart: true
    volumes:
      - $HOME/.snowflake:/root/.snowflake
      - $PWD/data_processing/crypto_wallet.json:/trading_bot/crypto_wallet.json
      - $PWD/hyperliquid_id.json:/trading_bot/hyperliquid_id.json