services:
  extraction:
    image: extract:latest
    volumes:
      - /Users/adm1n/Data/Projets/CryptoBot/data_processing:/data_collection
      - /Users/adm1n/.aws:/root/.aws
  transformation:
    image: transform:beta
    volumes:
      - /Users/adm1n/.aws:/root/.aws
  loading:
    image: load:latest
    volumes:
      - /Users/adm1n/.snowflake:/root/.snowflake
      - /Users/adm1n/Data/Projets/CryptoBot/data_processing:/data_loading
